### ISSUE TITLE
Our LDAP requires a password to connect

### ISSUE THREAD

**Issue by deada92** [thm-projects/arsnova-backend#29]
Hello guys,

I'm currently trying to setup LDAP for arsnova. Here's what I have done so for:

**arsnova-customization**
I have deployed the customization files to tomcat and modified the "apiPath" variable in **account.html** to the arsnova-backend path.

**arsnova-properties**
I have modified the arsnova-properties LDAP section to the following:

```json
# LDAP authentication
#
# Specific parameters:
# url: LDAP server URL
# user-dn-pattern: Pattern used to check user credentials against the LDAP
#     server. {0} will be replaced with the user ID by ARSnova.
#
security.ldap.enabled=true
security.ldap.title=Mit RUB Login
security.ldap.login-dialog-path=account.html
security.ldap.image=/rub-logo.png
security.ldap.order=0
security.ldap.url=ldaps://ldap.xxx:636/cn=xxx,ou=sicherheit,dc=xxx,dc=de
security.ldap.user-dn-pattern=uid={0},ou=users,dc=xxx,dc=de
# Not yet implemented parameters
#security.ldap.user-search-filter=(uid={0})
#security.ldap.user-search-base="ou=people"
```

So the Login is  failing and I think because our LDAP Server requires a password to authenticate. Is there a way to set that?

BTW: Is there a special way to set the image (security.ldap.image)? Because what I did don't display the image..

**Logs**

```json
11:08:56,905  INFO http-bio-8080-exec-31 ldap.DefaultSpringSecurityContextSource:59 -  URL 'ldaps://ldap.xxx:636/cn=xxx,ou=sicherheit,dc=xxx,dc=de', root DN is 'cn=xxx,ou=sicherheit,dc=xxx,dc=de'
11:08:56,913  INFO http-bio-8080-exec-31 support.AbstractContextSource:420 - Property 'userDn' not set - anonymous context will be used for read-write operations
11:08:56,938  INFO http-bio-8080-exec-31 userdetails.DefaultLdapAuthoritiesPopulator:167 - groupSearchBase is null. No group search will be performed.
11:08:56,948  INFO http-bio-8080-exec-31 config.SecurityConfig:167 - Enabled authentication providers: [user-db, ldap]
```

When I log in:
```json
11:16:30,313  WARN ajp-bio-8009-exec-114 annotation.ExceptionHandlerExceptionResolver:186 - Handler execution resulted in exception: null
11:19:55,629  INFO ajp-bio-8009-exec-240 controller.LoginController:172 - Authentication failed: Bad credentials
```

**Comment by deada92** [comment]
Is this commit (https://github.com/thm-projects/arsnova-backend/commit/e487c745bab604c20f35aa28c35b2a9aee258e95) maybe what I need?

**Comment by deada92** [comment]
I have now cloned this repository into eclipse and rebuild the war archive with the new commit. It deployed successfully and everything is working except the LDAP-Login.

Here is my new LDAP-Section:

```json
security.ldap.enabled=true
security.ldap.title=RZ-Login
security.ldap.login-dialog-path=account.html
security.ldap.image=images/rub-logo.png
security.ldap.order=0
security.ldap.url=ldaps://ldap.xxx:636/dc=xxx,dc=de
security.ldap.user-dn-pattern=uid={0},ou=users
# Set the following properties if you want to use LDAP search instead of binding
# with a DN pattern
#security.ldap.user-search-filter=(uid={0})
#security.ldap.user-search-base="ou=users"
# Configure the LDAP manager user if anonymous binding is not allowed
security.ldap.manager-user-dn=cn=xxx,dc=xxx,dc=de
security.ldap.manager-password=xxx
```

**Comment by pcvolkmer** [comment]
Please try
```
security.ldap.manager-user-dn=cn=<x username x>
security.ldap.manager-password=<x password x>
```
-> Do not append `dc=xxx,dc=de` in `security.ldap.manager-user-dn`.
I could not check right now, but it might work. Please report if successful.

**Comment by deada92** [comment]
Did what you said @pcvolkmer .. unfortunately not successfull

**Comment by pcvolkmer** [comment]
You could also try:
```
security.ldap.url=ldaps://ldap.xxx:636/
security.ldap.user-dn-pattern=uid={0},ou=users,dc=xxx,dc=de
...
security.ldap.user-search-base="ou=users",dc=xxx,dc=de
...
security.ldap.manager-user-dn=cn=xxx,dc=xxx,dc=de
security.ldap.manager-password=xxx
```

I guess it's about adding base path to LDAP-URL. My be Logs give a hint. There you should find some information from Spring Security if login fails.

**Comment by deada92** [comment]
Sorry for the late response but your advice didn't helped :( 

The Logs didn't really write something new but the ones I wrote above:  

**Logs**

```json
11:08:56,905  INFO http-bio-8080-exec-31 ldap.DefaultSpringSecurityContextSource:59 -  URL 'ldaps://ldap.xxx:636/cn=xxx,ou=sicherheit,dc=xxx,dc=de', root DN is 'cn=xxx,ou=sicherheit,dc=xxx,dc=de'
11:08:56,913  INFO http-bio-8080-exec-31 support.AbstractContextSource:420 - Property 'userDn' not set - anonymous context will be used for read-write operations
11:08:56,938  INFO http-bio-8080-exec-31 userdetails.DefaultLdapAuthoritiesPopulator:167 - groupSearchBase is null. No group search will be performed.
11:08:56,948  INFO http-bio-8080-exec-31 config.SecurityConfig:167 - Enabled authentication providers: [user-db, ldap]
```

When I log in:
```json
11:16:30,313  WARN ajp-bio-8009-exec-114 annotation.ExceptionHandlerExceptionResolver:186 - Handler execution resulted in exception: null
11:19:55,629  INFO ajp-bio-8009-exec-240 controller.LoginController:172 - Authentication failed: Bad credentials
```

Any Idea @pcvolkmer @dgerhardt ?

**Comment by dgerhardt** [comment]
It looks like the DB authentication is used instead of LDAP. `account.html` is used for either but you have to slightly adjust it for LDAP. Make use that `type` is set to `ldap`: https://github.com/thm-projects/arsnova-customization/blob/master/src/main/webapp/account.html#L204

**Comment by deada92** [comment]
Hey @dgerhardt ,

thx for the hint. I did that and now the Error Logs display more. Here is my Arsnova propertie file first::

**Arsnova LDAP**

```
# LDAP authentication
#
# Specific parameters:
# url: LDAP server URL
# user-dn-pattern: Pattern used to check user credentials against the LDAP
#     server. {0} will be replaced with the user ID by ARSnova.
#
security.ldap.enabled=true
security.ldap.title=RZ-Login
security.ldap.login-dialog-path=account.html
security.ldap.image=images/rub-logo.png
security.ldap.order=0
security.ldap.url=ldaps://ldap.xxx:636/ou=users,dc=xxx,dc=de
security.ldap.user-dn-pattern=uid={0},ou=users,dc=xxx,dc=de
# Set the following properties if you want to use LDAP search instead of binding
# with a DN pattern
security.ldap.user-search-filter=(uid={0})
security.ldap.user-search-base="ou=users,dc=xxx,dc=de"
# Configure the LDAP manager user if anonymous binding is not allowed
security.ldap.manager-user-dn=cn=xxx,ou=sicherheit,dc=xxx,dc=de
security.ldap.manager-password=xxx
```

**Logs**
```json
12:15:33,686  INFO ajp-bio-8009-exec-7 controller.LoginController:197 - No LDAP login: {}
org.springframework.security.authentication.InternalAuthenticationServiceException: [LDAP: error code 32 - LDAP Error 32 : No Such Object]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - LDAP Error 32 : No Such Object]; remaining name 'ou=users,dc=xxx,dc=de'
        at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:208)
        at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:82)
        at de.thm.arsnova.controller.LoginController.doLogin(LoginController.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at de.thm.arsnova.web.CorsFilter.doFilterInternal(CorsFilter.java:47)

Caused by: org.springframework.ldap.NameNotFoundException: [LDAP: error code 32 - LDAP Error 32 : No Such Object]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - LDAP Error 32 : No Such Object]; remaining name 'ou=users,dc=xxx,dc=de'
        at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:183)
        at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:820)
        at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:803)
        at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntry(SpringSecurityLdapTemplate.java:316)
        at org.springframework.security.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:126)
        at org.springframework.security.ldap.authentication.BindAuthenticator.authenticate(BindAuthenticator.java:94)
        at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:189)
        ... 70 more
Caused by: javax.naming.NameNotFoundException: [LDAP: error code 32 - LDAP Error 32 : No Such Object]; remaining name 'ou=users,dc=xxx,dc=de'
        at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3112)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3033)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2840)
        at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1849)
        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1772)
        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1789)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:412)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:394)
        at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:297)
        at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntryInternal(SpringSecurityLdapTemplate.java:333)
        at org.springframework.security.ldap.SpringSecurityLdapTemplate$3.executeWithContext(SpringSecurityLdapTemplate.java:318)
        at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:817)
```

Google tells that it has a connection with a error that occurs when adding a User to LDAP. Our LDAP contains every User... Is that possible? I'm I right?

**Comment by dgerhardt** [comment]
I think you have to remove the base path from the URL as suggested by @pcvolkmer since you have already set it as part of search base.

**Comment by deada92** [comment]
We are getting to it. I get now this Error:

```
org.springframework.ldap.NoPermissionException: [LDAP: error code 50 - LDAP Error 50 : Insufficient Access Rights]; nested exception is javax.naming.NoPermissionException: [LDAP: error code 50 - LDAP Error 50 : Insufficient Access Rights]; remaining name 'uid=yyy,ou=users,dc=yyy,dc=de'
        at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:188)
        at org.springframework.security.ldap.authentication.BindAuthenticator.bindWithDn(BindAuthenticator.java:148)
        at org.springframework.security.ldap.authentication.BindAuthenticator.authenticate(BindAuthenticator.java:95)
        at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:189)
        ... 70 more
Caused by: javax.naming.NoPermissionException: [LDAP: error code 50 - LDAP Error 50 : Insufficient Access Rights]; remaining name 'uid=yyy,ou=users,dc=yyy,dc=de'
        at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3095)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3033)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2840)
        at com.sun.jndi.ldap.LdapCtx.c_getAttributes(LdapCtx.java:1332)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:231)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:139)
        at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:152)
        at org.springframework.security.ldap.authentication.BindAuthenticator.bindWithDn(BindAuthenticator.java:124)
        ... 72 more
                                    
``` 

I found this on [Stackoverflow](http://stackoverflow.com/questions/22632607/ldap-error-code-50-the-entry-uid-testinfo-com-ou-people-o-drive-dc-company-d) and as I see it is Arsnova try to Add/Edit the LDAP, right?

**Comment by dgerhardt** [comment]
ARSnova does not need write access on the LDAP server. It either directly performs an LDAP bind with user credentials using `user-dn-pattern` or it performs a bind with manager credentials, searches for the user object and then uses its DN to perform a bind.

It looks like the manager account is not allowed to perform the bind with the user's DN and so the last step fails.

**Comment by deada92** [comment]
mhh I understand. So in which scenario does this work? Why does someone need to search first if the he knows the uid? Isn't it the same like logging in with just the user-dn-pattern? I mean at the end you do the same, right?

**Comment by tekay** [comment]
Some LDAP Server allow an anonymous bind (what you suggested). But if anon bind is restricted, you need to search the entry in your directory via manager account and let the user verify against the entry (instead of login into the LDAP Server directly).

**Comment by dgerhardt** [comment]
You use search in case the user DN cannot be inferred from the credentials. Use cases:
* The OU parts in the user DN aren't fixed.  
(e.g. `uid=user1,ou=dept1,dc=...` and `uid=user2,ou=dept2,dc=...`)
* The UID isn't used for logging in.  
(e.g. log in with e-mail address)

**Comment by dgerhardt** [comment]
I'm closing this for now since the discussion has moved away from ARSnova's LDAP implementation to general LDAP authentication concepts.

**Comment by deada92** [comment]
Hello @dgerhardt,

I hope you had a good start in the new year!

Our LDAP-Admin and I had a discussion and he explained to me that our LDAP doesn't allow a self search. For this situation we have a have a binduser of another `ou`. This one requires a password. Can I set it for the search user in arsnova?

**Comment by deada92** [comment]
Is it possible to search with the manager-user?

**Comment by tekay** [comment]
"But if anon bind is restricted, you need to search the entry in your directory via manager account [...]"

Yes, it is possible, that's exactly what it's made for ;-)

**Comment by deada92** [comment]
Well if you say so why doesnt it work? I have probably  used every combination of arsnova properties that is possible. I tried to connect with openldap from my server and I have got a result. Also other application is able to connect.

Which properties and format of the values do I have to use that arsnova is able to search the user with the manager dn & passwort? Would be cool if you can give me a example or better modify my arsnova propertie file from my first post.

**Comment by deada92** [comment]
No idea ? :(
