### ISSUE TITLE
backend throws json errors and mobile throws websocket errors

### ISSUE THREAD

**Issue by SaifAlDilaimi** [thm-projects/arsnova-backend#55]
I'm trying to solve the following errors for the last 12 hours but with no luck:

Mobile Version: 2.5.2
Backend Version: 2.5.4

Issue 1: *WebSocket connection to 'wss://arsnova.rub.de/socket.io/' failed: Error during WebSocket handshake: Unexpected response code: 502*

According to the installation guide I have set following nginx rules and arsnova properties:

```
server {
        listen 80 default_server;
        server_name arsnova.rub.de arsnova.ruhr-uni-bochum.de arsnova.rubel.rub.de arsnova2.rubel.rub.de www.arsnova2.rubel.rub.de;


location /socket.io/ {
        proxy_pass http://localhost:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
}

rewrite ^/(.*)$ https://arsnova.rub.de/$1 permanent;

}

server{
  listen 443;
  server_name arsnova.rub.de arsnova.ruhr-uni-bochum.de arsnova.rubel.rub.de arsnova2.rubel.rub.de www.arsnova2.rubel.rub.de;

#    ssl_certificate           /etc/pki/tls/certs/arsnova/cert-9024836910352930975887833388.pem;
    ssl_certificate           /etc/pki/tls/certs/arsnova/trust-chain-arsnova.pem;
    ssl_certificate_key       /etc/pki/tls/certs/arsnova/priv_key_unlocked.pem;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/jenkins.access.log;
    keepalive_timeout 300000;

location = / { return 301 https://arsnova.rub.de/mobile; }

location = /arsnova-config { proxy_pass http://localhost:8080/api/configuration/; }

location /api {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
}

location /socket.io/ {
        proxy_pass http://localhost:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
}
```

the relevant properties are:

```
root-url=https://arsnova.rub.de

# The path where the ARSnova API is accessible by clients. By default, this path
# is set to the context path of the backend. If you are running the backend
# behind a proxy server, you might need to set this path manually.
api.path=/api

# The context paths where the ARSnova modules have been deployed
customization.path=/customization
mobile.path=/mobile
presenter.path=/presenter

# WebSockets server
socketio.bind-address=localhost
socketio.port=8090
# SSL/TLS configuration
# To enable SSL for Socket.IO you have to import your key and certificate files into a Java Key Store. If you tunnel
# WebSocket connections through a proxy server, you can skip this configuration.
# See https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html
socketio.ssl.jks-file=/etc/arsnova/keystore.ks
socketio.ssl.jks-password=xyz
socketio.proxy-path=/socket.io
```

I'm not sure if issue 2 is just a follow up error of issue 1 but i'm getting follow JSON Array error:

```

05:39:07,533 ERROR pool-2-thread-1 dao.CouchDBDao:1351 - Error while retrieving session count
net.sf.json.JSONException: JSONObject["rows"] is not a JSONArray.
        at net.sf.json.JSONObject.getJSONArray(JSONObject.java:2036)
        at com.fourspaces.couchdb.ViewResults.getResults(ViewResults.java:65)
        at de.thm.arsnova.dao.CouchDBDao.isEmptyResults(CouchDBDao.java:1082)
        at de.thm.arsnova.dao.CouchDBDao.getStatistics(CouchDBDao.java:1294)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:342)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:405)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:324)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy34.getStatistics(Unknown Source)
        at de.thm.arsnova.services.StatisticsService.refreshStatistics(StatisticsService.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
05:39:07,536  INFO pool-2-thread-1 services.UserService:172 - Delete inactive users.
05:39:25,090 ERROR http-nio-8080-exec-3 couchdb.Session:475 - java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

```

Any help would be awesome. Its really urgent because our system is not working because of those errors....

**Comment by dgerhardt** [comment]
> Unexpected response code: 502

The proxy connection Nginx <-> Websocket backend fails.

```
proxy_pass http://localhost:8090;
```

```
socketio.ssl.jks-file=/etc/arsnova/keystore.ks
socketio.ssl.jks-password=xyz
```

Nginx tries to connect through unencrypted HTTP but the Websocket backend is set up for SSL. You should disable the `socketio.ssl` settings.

> I'm not sure if issue 2 is just a follow up error of issue 1 but i'm getting follow JSON Array error

This issue isn't related to the first one. But I need more context here. Is this happening on a fresh installation or is this an upgrade from an older version? If you upgraded, did you run the migration script?

**Comment by SaifAlDilaimi** [comment]
hey @dgerhardt ,

if I comment out those two settings I get following error:

`WebSocket connection to 'wss://arsnova.rub.de/socket.io/' failed: HTTP Authentication failed; no valid credentials available`

I have upgraded from 2.4 to 2.5, downloaded setup tool for 2.5 and run tool.py. it generated few views (5 or 6). After that I started migration.py but after 4 hours it was just at `Migrating all Question documents...` nothing. Although the second error was there also before upgrading.

**Comment by SaifAlDilaimi** [comment]
hello @dgerhardt , after finding out that my server seems not to start any indexing process I have moved my couchdb database from the redhat to a ubuntu system. The indexing started and migrated successfully. Although after logging in and clicking on a session as teacher I'm getting redirected to the first page where I can choose my role. The strange thing is that it happens only on chrome (tested on multiple systems). Safari, Firefox and Vivaldi (which is based on chromium) redirect to the session correctly. Is anything in my nginx conf wrong?

```
server {
        listen 80 default_server;
        server_name arsnova.rub.de arsnova.ruhr-uni-bochum.de arsnova.rubel.rub.de arsnova2.rubel.rub.de www.arsnova2.rubel.rub.de;

rewrite ^/(.*)$ https://arsnova.rub.de/$1 permanent;

}

server{
  listen 443;
  server_name arsnova.rub.de arsnova.ruhr-uni-bochum.de arsnova.rubel.rub.de arsnova2.rubel.rub.de www.arsnova2.rubel.rub.de;

    ssl_certificate           /etc/pki/tls/certs/arsnova/trust-chain-arsnova.pem;
    ssl_certificate_key       /etc/pki/tls/certs/arsnova/priv_key_unlocked.pem;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/jenkins.access.log;
    keepalive_timeout 300000;

location = / { return 301 https://arsnova.rub.de/mobile; }

location = /arsnova-config { proxy_pass http://localhost:8080/api/configuration/; }

location /api {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
}

location /socket.io/ {
        proxy_pass http://localhost:8090;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
}

location /mobile { proxy_pass http://localhost:8080/mobile; }

location /customization { proxy_pass http://localhost:8080/customization; }
```

**Comment by dgerhardt** [comment]
> Although after logging in and clicking on a session as teacher I'm getting redirected to the first page where I can choose my role. The strange thing is that it happens only on chrome

It's a bug in Chrome 65 and 66. The current version of ARSnova Mobile has a workaround for this browser bug.

**Comment by SaifAlDilaimi** [comment]
@dgerhardt thank you very much. You got now 2 🍺 on me as soon as you are in Bochum ;)
