### ISSUE TITLE
successfulFreeTextAnswer not created after migration

### ISSUE THREAD

**Issue by dhx** [thm-projects/arsnova-backend#58]
After the upgrade to 2.6 we see errors as the successfulFreeTextAnswer key is not existing in old question responses, see:

```
2018-08-29 15:18:21 ERROR ajp-bio-8009-exec-5 controller.AbstractControllerExceptionHandler:33 - JSONArray[3] is not a Boolean.
net.sf.json.JSONException: JSONArray[3] is not a Boolean.
        at net.sf.json.JSONArray.getBoolean(JSONArray.java:1904)
        at de.thm.arsnova.dao.CouchDBDao.getAllAnswers(CouchDBDao.java:1036)
        at sun.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy35.getAllAnswers(Unknown Source)
        at de.thm.arsnova.services.QuestionService.getAllAnswers(QuestionService.java:463)
        at sun.reflect.GeneratedMethodAccessor308.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy52.getAllAnswers(Unknown Source)
        at de.thm.arsnova.controller.LecturerQuestionController.getAnswers(LecturerQuestionController.java:439)
        at de.thm.arsnova.controller.LecturerQuestionController$$FastClassBySpringCGLIB$$3695a666.invoke(<generated>)
```

**Comment by dgerhardt** [comment]
Thank you for reporting this issue. I've pushed a fix for the CouchDB view of ARSnova Setuptool. `successfulFreeTextAnswer` now defaults to `false`.

**Comment by dhx** [comment]
Thanks for the fast fix
